apiVersion: batch/v1
kind: Job
metadata:
  name: gcs-smoke
  namespace: rnaseq
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: airflow-runner
      restartPolicy: Never
      containers:
      - name: gcloud
        image: google/cloud-sdk:latest   # has gcloud + gsutil
        command: ["bash","-lc"]
        env:
        - name: BUCKET
          value: "{{BUCKET}}"
          args:
          - |
            set -euo pipefail
            echo "BUCKET=$BUCKET"
            : "${BUCKET:?BUCKET not set}"
            /usr/bin/gsutil ls -d "gs://${BUCKET}"
            date | /usr/bin/gsutil cp - "gs://${BUCKET}/tmp/w2d1.txt"
            /usr/bin/gsutil ls -l "gs://${BUCKET}/tmp/w2d1.txt"
      resources:
          requests: { cpu: "100m", memory: "128Mi" }
          limits:   { cpu: "500m", memory: "512Mi" }
