name: ruff
on:
  push:
    branches: [main]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Lint
      - uses: astral-sh/ruff-action@v1
        with:
          version: "0.5.7"     # (no leading "v")
          args: "check ."

      # Format check (optional, fails on unformatted code)
      - uses: astral-sh/ruff-action@v1
        with:
          version: "0.5.7"
          args: "format --check ."
